language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
install:
  - "pip3 install pep8"
  - "pip3 install -r requirements.txt"
  - "pip3 install -r requirements-dev.txt"
script:
  - "coverage run --source=dotinstall tests.py"
after_success:
  coveralls
sudo: required
