language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
install:
  - "pip3 install pep8"
  - "pip3 install tox-travis"
  - "pip3 install -rrequirements.txt"
  - "pip3 install -rrequirements-dev.txt"
script:
  - "tox"
after_success:
  coveralls
sudo: required
