language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
install:
  - "pip3 install pep8"
  - "pip3 install -r requirements.txt"
script:
  - "chmod +x ./tests.sh"
  - "./tests.sh"
sudo: required
