test:
  prelink:
    - "mkdir ./dist"
    - "echo 100 > ./dist/1.txt"
    - "echo 200 > ./dist/2.txt"
    - "touch ./test/broken1.txt"
    - "touch ./test/broken2.txt"
  link:
    - "*1.txt": "./dist"
    - "*": "./other_dist"
    - ".*": "./other_dist"
  postlink:
    - "rm ./other_dist/3.txt"
    - "rm ./test/broken1.txt"
    - "rm ./test/broken2.txt"
    - "cat ./dist/1.txt"
    - "ls ./dist"
